version: 0.0
os: linux

files:
  - source: /dist
    destination: /var/www/html/dist

hooks:
  ApplicationStart:
      timeout: 300
      runas: root
      command:
        - sudo npm start

  ApplicationStop:
      timeout: 300
      runas: root
      command:
        - sudo fuser -k 3000/tcp