version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/dist

hooks:
  ApplicationStart:
    - location: scripts/deploy/dev/application_start.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/deploy/dev/application_stop.sh
      timeout: 300
      runas: root