version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/deploy/dev/before_install.sh
      timeout: 300

  AfterInstall:
    - location: scripts/deploy/dev/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/deploy/dev/application_start.sh
      timeout: 300