version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @nestjs/cli

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - nest build

artifacts:
  files:
    - '**/*'
  base-directory: './dist'
